// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    App: typeof import('./../App.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    Header: typeof import('./../views/layout/Header.vue')['default']
    Home: typeof import('./../views/pages/home/home.vue')['default']
    KeepAliveView: typeof import('./../views/layout/KeepAliveView.vue')['default']
    Login: typeof import('./../views/pages/login/login.vue')['default']
    LyIcon: typeof import('./../components/LyIcon.vue')['default']
    NavigateList: typeof import('./../views/layout/NavigateList.vue')['default']
    PageHeader: typeof import('./../components/PageHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./../views/layout/SideBar/index.vue')['default']
  }
}
