// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core';

export {};

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    App: typeof import('./../App.vue')['default'];
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider'];
    Header: typeof import('./../views/layout/Header/index.vue')['default'];
    RouterLink: typeof import('vue-router')['RouterLink'];
    RouterView: typeof import('vue-router')['RouterView'];
    SideBar: typeof import('./../views/layout/SideBar/index.vue')['default'];
  }
}
